### ISSUE TITLE
NameReg?

### ISSUE THREAD

**Issue by rfikki** [WeiFund/WeiFund#13]
Why are you not using the Global Official Name Registry? Just Curious.

**Comment by SilentCicero** [comment]
@rfikki I believe global NameReg still has some conflicting designs with WeiFund. I'm using a bytes32 namereg, I think they are using a string namereg. I could be wrong. But naturally, I'll integrate the global namereg when I can and when it makes sense to do so. Valid point none the less.

**Comment by rfikki** [comment]
Hi Nick.
I am very interested in your project and want to make sure it succeeds. The global registry is in place now, and will be released as part of geth v1.3.0.
For now you can set these manually.

admin.setGlobalRegistrar("0x33990122638b9132ca29c723bdf037f1a891a70c")
admin.setHashReg("0x23bf622b5a65f6060d855fca401133ded3520620")
admin.setUrlHint("0x73ed5ef6c010727dfd2671dbb70faac19ec18626")

For mor info see: https://github.com/ethereum/go-ethereum/pull/1840/files#diff-591d794d5247448444354652052633ccR57
