### ISSUE TITLE
Meteor Freezes at download of packages in Ubuntu

### ISSUE THREAD

**Issue by rfikki** [WeiFund/WeiFund#17]

**Comment by SilentCicero** [comment]
Hi, remove the test packages and see if you can get it running. It isn't Freezing necessarily, it's just taking forever to download testrpc =D (2mb).

**Comment by SilentCicero** [comment]
I've taken off those large packages for now. They may be best used as a file and not a Meteor package. TestRPC literally includes an entire eth-node.

**Comment by rfikki** [comment]
Yes, that was a large download. Thanks for the response.
