### ISSUE TITLE
I am getting a compilation error as seen below

### ISSUE THREAD

**Issue by rfikki** [WeiFund/WeiFund#18]
Error compiling:

WeiFundTokenFactory.sol:126:9: Error: Identifier already declared.
        address newTokenAddr = address(new Standard_Token(_initialAmount));
        ^------------------^
The previous declaration is here: WeiFundTokenFactory.sol:125:83:
    function createStandardToken(address _owner, uint256 _initialAmount) returns                                        (address newTokenAddr) {
                                                                                                                         ^------------------^

,WeiController.sol:299:3: Error: Operator += not compatible with types address a                                       nd uint256
                total_issued += tokenAmount;
                ^-------------------------^
,WeiControllerFactory.sol:299:3: Error: Operator += not compatible with types ad                                       dress and uint256
                total_issued += tokenAmount;
                ^-------------------------^
Compiliation failed.

**Comment by SilentCicero** [comment]
Hey @rfikki not sure. I'm going to take a look today.
