### ISSUE TITLE
error when i try to make campaign?

### ISSUE THREAD

**Issue by Shadowstep33** [WeiFund/WeiFund#19]
I set my beneficiary account and I am using the WeiFund set token controller and standard token. When I try to submit, it says error. The selected acc says 0x0000000000000000000000000000000000000000 and that i have enough shannon in my account, but clearly that doesn't seem to actually be an account. I am very new to cryptos but overall it seems like an error; possibly in my configuration?

**Comment by SilentCicero** [comment]
@Shadowstep33 so account '0x000..' is not an account you own. It's an empty account no one owns on Ethereum. It looks like your using the Etherscan provider which is "read-only" at this point.

If you want to use your own account, you need to run your own testnet node, create an account and faucet ether to it.

Thanks for checking out weifund !

I'll add in a feature to let people know about the account "0x000..", cheers

**Comment by Shadowstep33** [comment]
All of that makes 0 sense to me, but that was a very informative reply. I will look into creating my own testnet node thanks!
