### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by TOMOAKI12345** [WeiFund/WeiFund#2]
business
![screen shot 2015-05-12 at 9 26 51 pm](https://cloud.githubusercontent.com/assets/2216012/7587002/ba8d1198-f8ed-11e4-9d4b-1bdc24ab7950.png)

**Comment by SilentCicero** [comment]
Will fix on next commit. Cheers!

**Comment by SilentCicero** [comment]
Fixed in latest commit.
