### ISSUE TITLE
WeiControllerFactory.sol

### ISSUE THREAD

**Issue by rfikki** [WeiFund/WeiFund#27]
Again I wanted to let you know that your code has an error:	
line 257 should be changed it is not an address type, but it should be uint.
- address public total_issued;
+ uint public total_issued;

**Comment by SilentCicero** [comment]
fixed, thanks @rfikki - but it has been fixed in the actual contracts folder in the client lib. That is just a display copy (it was old).

**Comment by rfikki** [comment]
ah, sorry. was testing the contracts in that folder....
